proto_library(
    name = "leds_proto",
    srcs = [
        "leds.proto"
    ]
)

cc_proto_library(
    name = "leds_cc_proto",
    deps = [
        ":leds_proto"
    ],
    visibility = ["//visibility:public"],
)
