# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: leds.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='leds.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\nleds.proto\"\xb8\x01\n\tLedStatus\x12\x1f\n\x07LedBlue\x18\x01 \x01(\x0e\x32\x0e.LedStatus.Led\x12\x1e\n\x06LedRed\x18\x02 \x01(\x0e\x32\x0e.LedStatus.Led\x12!\n\tLedOrange\x18\x03 \x01(\x0e\x32\x0e.LedStatus.Led\x12 \n\x08LedGreen\x18\x04 \x01(\x0e\x32\x0e.LedStatus.Led\"%\n\x03Led\x12\r\n\tNO_CHANGE\x10\x00\x12\x06\n\x02ON\x10\x01\x12\x07\n\x03OFF\x10\x02\x62\x06proto3'
)



_LEDSTATUS_LED = _descriptor.EnumDescriptor(
  name='Led',
  full_name='LedStatus.Led',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NO_CHANGE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ON', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='OFF', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=162,
  serialized_end=199,
)
_sym_db.RegisterEnumDescriptor(_LEDSTATUS_LED)


_LEDSTATUS = _descriptor.Descriptor(
  name='LedStatus',
  full_name='LedStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='LedBlue', full_name='LedStatus.LedBlue', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='LedRed', full_name='LedStatus.LedRed', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='LedOrange', full_name='LedStatus.LedOrange', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='LedGreen', full_name='LedStatus.LedGreen', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _LEDSTATUS_LED,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=199,
)

_LEDSTATUS.fields_by_name['LedBlue'].enum_type = _LEDSTATUS_LED
_LEDSTATUS.fields_by_name['LedRed'].enum_type = _LEDSTATUS_LED
_LEDSTATUS.fields_by_name['LedOrange'].enum_type = _LEDSTATUS_LED
_LEDSTATUS.fields_by_name['LedGreen'].enum_type = _LEDSTATUS_LED
_LEDSTATUS_LED.containing_type = _LEDSTATUS
DESCRIPTOR.message_types_by_name['LedStatus'] = _LEDSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LedStatus = _reflection.GeneratedProtocolMessageType('LedStatus', (_message.Message,), {
  'DESCRIPTOR' : _LEDSTATUS,
  '__module__' : 'leds_pb2'
  # @@protoc_insertion_point(class_scope:LedStatus)
  })
_sym_db.RegisterMessage(LedStatus)


# @@protoc_insertion_point(module_scope)
